# MAIN PROJECT
20BCE1714

UJJWAL KANTI PRAMANICK

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelBinarizer

## Importing the dataset

In [ ]:
dataset = pd.read_csv('car_price_dataset.csv',index_col=0)
dataset

Name    Location  Year  Kilometers_Driven  \
0               Maruti Wagon R LXI CNG      Mumbai  2010              72000   
1     Hyundai Creta 1.6 CRDi SX Option        Pune  2015              41000   
2                         Honda Jazz V     Chennai  2011              46000   
3                    Maruti Ertiga VDI     Chennai  2012              87000   
4      Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   
...                                ...         ...   ...                ...   
6014                  Maruti Swift VDI       Delhi  2014              27365   
6015          Hyundai Xcent 1.1 CRDi S      Jaipur  2015             100000   
6016             Mahindra Xylo D4 BSIV      Jaipur  2012              55000   
6017                Maruti Wagon R VXI     Kolkata  2013              46000   
6018             Chevrolet Beat Diesel   Hyderabad  2011              47000   

     Fuel_Type Transmission Owner_Type     Mileage   Engine      Power  Seats  \
0          CNG       Manual      First  26.6 km/kg   998 CC  58.16 bhp    5.0   
1       Diesel       Manual      First  19.67 kmpl  1582 CC  126.2 bhp    5.0   
2       Petrol       Manual      First   18.2 kmpl  1199 CC   88.7 bhp    5.0   
3       Diesel       Manual      First  20.77 kmpl  1248 CC  88.76 bhp    7.0   
4       Diesel    Automatic     Second   15.2 kmpl  1968 CC  140.8 bhp    5.0   
...        ...          ...        ...         ...      ...        ...    ...   
6014    Diesel       Manual      First   28.4 kmpl  1248 CC     74 bhp    5.0   
6015    Diesel       Manual      First   24.4 kmpl  1120 CC     71 bhp    5.0   
6016    Diesel       Manual     Second   14.0 kmpl  2498 CC    112 bhp    8.0   
6017    Petrol       Manual      First   18.9 kmpl   998 CC   67.1 bhp    5.0   
6018    Diesel       Manual      First  25.44 kmpl   936 CC   57.6 bhp    5.0   

      Price  
0      1.75  
1     12.50  
2      4.50  
3      6.00  
4     17.74  
...     ...  
6014   4.75  
6015   4.00  
6016   2.90  
6017   2.65  
6018   2.50  

[6019 rows x 12 columns]

In [ ]:
dataset['Power'].unique

<bound method Series.unique of 0       58.16 bhp
1       126.2 bhp
2        88.7 bhp
3       88.76 bhp
4       140.8 bhp
          ...    
6014       74 bhp
6015       71 bhp
6016      112 bhp
6017     67.1 bhp
6018     57.6 bhp
Name: Power, Length: 6019, dtype: object>

In [ ]:
dataset.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
Price                float64
dtype: object

In [ ]:
dataset.isna().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               36
Power                36
Seats                42
Price                 0
dtype: int64

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1:].values
print(X)

[['Maruti Wagon R LXI CNG' 'Mumbai' 2010 ... '998 CC' '58.16 bhp' 5.0]
 ['Hyundai Creta 1.6 CRDi SX Option' 'Pune' 2015 ... '1582 CC'
  '126.2 bhp' 5.0]
 ['Honda Jazz V' 'Chennai' 2011 ... '1199 CC' '88.7 bhp' 5.0]
 ...
 ['Mahindra Xylo D4 BSIV' 'Jaipur' 2012 ... '2498 CC' '112 bhp' 8.0]
 ['Maruti Wagon R VXI' 'Kolkata' 2013 ... '998 CC' '67.1 bhp' 5.0]
 ['Chevrolet Beat Diesel' 'Hyderabad' 2011 ... '936 CC' '57.6 bhp' 5.0]]


In [ ]:
print(y)

[[ 1.75]
 [12.5 ]
 [ 4.5 ]
 ...
 [ 2.9 ]
 [ 2.65]
 [ 2.5 ]]


## Taking care of missing data

In [ ]:
np.count_nonzero(pd.isna(X))

116

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X[:, 7:11])
X[:, 7:11] = imputer.transform(X[:, 7:11])

In [ ]:
np.count_nonzero(pd.isna(X))

0

## removing units 

In [ ]:
X

array([['Maruti Wagon R LXI CNG', 'Mumbai', 2010, ..., '998 CC',
        '58.16 bhp', 5.0],
       ['Hyundai Creta 1.6 CRDi SX Option', 'Pune', 2015, ..., '1582 CC',
        '126.2 bhp', 5.0],
       ['Honda Jazz V', 'Chennai', 2011, ..., '1199 CC', '88.7 bhp', 5.0],
       ...,
       ['Mahindra Xylo D4 BSIV', 'Jaipur', 2012, ..., '2498 CC',
        '112 bhp', 8.0],
       ['Maruti Wagon R VXI', 'Kolkata', 2013, ..., '998 CC', '67.1 bhp',
        5.0],
       ['Chevrolet Beat Diesel', 'Hyderabad', 2011, ..., '936 CC',
        '57.6 bhp', 5.0]], dtype=object)

In [ ]:
X[:,7]=(np.array([ np.array(i)[0] for i in np.char.split(X[:,7].astype(str)) ]).astype(float))
X[:,8]=(np.array([ np.array(i)[0] for i in np.char.split(X[:,8].astype(str)) ]).astype(int))
X[:,9]=(np.array([ 98.6 if (np.array(i)[0]=='null') else  np.array(i)[0] for i in np.char.split(X[:,9].astype(str)) ]).astype(float))

In [ ]:
X

array([['Maruti Wagon R LXI CNG', 'Mumbai', 2010, ..., 998, 58.16, 5.0],
       ['Hyundai Creta 1.6 CRDi SX Option', 'Pune', 2015, ..., 1582,
        126.2, 5.0],
       ['Honda Jazz V', 'Chennai', 2011, ..., 1199, 88.7, 5.0],
       ...,
       ['Mahindra Xylo D4 BSIV', 'Jaipur', 2012, ..., 2498, 112.0, 8.0],
       ['Maruti Wagon R VXI', 'Kolkata', 2013, ..., 998, 67.1, 5.0],
       ['Chevrolet Beat Diesel', 'Hyderabad', 2011, ..., 936, 57.6, 5.0]],
      dtype=object)

In [ ]:
type(X)

numpy.ndarray

## encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelBinarizer()

In [ ]:
e0=lb.fit_transform(X[:,0])
e1=lb.fit_transform(X[:,1])
e4=lb.fit_transform(X[:,4])
e5=lb.fit_transform(X[:,5])
e6=lb.fit_transform(X[:,6])

In [ ]:
X=np.delete(X, [0,1,4,5,6], 1)

In [ ]:
X=np.concatenate((e0,e1,e4,e5,e6,X), axis=1)

In [ ]:
X

array([[0, 0, 0, ..., 998, 58.16, 5.0],
       [0, 0, 0, ..., 1582, 126.2, 5.0],
       [0, 0, 0, ..., 1199, 88.7, 5.0],
       ...,
       [0, 0, 0, ..., 2498, 112.0, 8.0],
       [0, 0, 0, ..., 998, 67.1, 5.0],
       [0, 0, 0, ..., 936, 57.6, 5.0]], dtype=object)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [ ]:
print(X_train)

[[0 0 0 ... 1798 138.1 5.0]
 [0 0 0 ... 2179 140.0 7.0]
 [0 0 0 ... 1341 83.0 5.0]
 ...
 [0 0 0 ... 998 67.1 5.0]
 [0 0 0 ... 2755 171.5 7.0]
 [0 0 0 ... 799 53.3 5.0]]


In [ ]:
print(X_test)

[[0 0 0 ... 2987 258.0 5.0]
 [0 0 0 ... 1586 104.68 5.0]
 [0 0 0 ... 1497 121.36 5.0]
 ...
 [0 0 0 ... 1498 99.0 5.0]
 [0 0 0 ... 1373 93.7 7.0]
 [0 0 0 ... 1197 82.0 5.0]]


In [ ]:
print(y_train)

[[ 5.2 ]
 [ 9.8 ]
 [ 0.45]
 ...
 [ 2.1 ]
 [19.64]
 [ 2.75]]


In [ ]:
print(y_test)

[[78.8 ]
 [ 3.51]
 [ 6.  ]
 ...
 [ 5.5 ]
 [ 5.5 ]
 [ 5.4 ]]


## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[24.89 78.8 ]
 [ 1.83  3.51]
 [14.08  6.  ]
 ...
 [ 2.93  5.5 ]
 [ 6.16  5.5 ]
 [ 5.75  5.4 ]]


In [ ]:
print(np.concatenate((y_pred, y_test),1))

[[24.89 78.8 ]
 [ 1.83  3.51]
 [14.08  6.  ]
 ...
 [ 2.93  5.5 ]
 [ 6.16  5.5 ]
 [ 5.75  5.4 ]]


In [ ]:
print(regressor.coef_)
print(regressor.intercept_)

[[ 1.13e+01  9.55e-01  2.41e+00 ... -1.16e-03  3.84e-02 -5.92e-01]]
[-1762.21]


# performance

In [ ]:
import math  
import sklearn.metrics   
mse = sklearn.metrics.mean_squared_error(y_test, y_pred)  
  
rmse = math.sqrt(mse)  
  
rmse

6.1652595185192345

# **THANK YOU**